### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by OlivineOverlord** [FrancescoPerrone/melt_maps#3]
get Dr. J's melts_map.yml working so everyone has the same versions for sklearn and skcmeans libraries.

- will be an issue for reproducible machine learning outputs

**Comment by FrancescoPerrone** [comment]
looks like yml needs fixed. some of the setting still point to @jeinsle  machine?

**Comment by jeinsle** [comment]
these are the directions

This notebook, is based on using Anaconda distributions of Python 3.0. sucessfull installation of the c-means code requires that the conda libary being the most current.

install python 3.x using anaconda (at time of writing this is 3.8) note it is also critcal to inusre that the conda is up todate Next steps are done from the anaconda terminal:
create a new python enviroment: conda create -n cmeans_env note cmeans_env is a dummy name for the clustering enviroment. Your choice what to call the enviroment.
install hyperspy (This will install Hyperspy and Sk-Learn): conda install hpyerspy -c condaforge
install cmeans (skcmeans): pip install https://github.com/bm424/scikitcmeans/archive/master.zip

**Comment by jeinsle** [comment]
what I would suggest is that instead of the yml we just follow these installation directions. There is some risk of libaries being diffent on different machines, but for the project as it stands now I think this is fine and should not be too big an issue.

**Comment by OlivineOverlord** [comment]
Dr J, you are a genius. What you suggested has worked!

I am not sure about @FrancescoPerrone but I am going to close this issue now

**Comment by FrancescoPerrone** [comment]
@joshjshea you mean you are not sure if I’m a genius :) it’s fine for me to close it as long as it works for you!
