### ISSUE TITLE
git login problems

### ISSUE THREAD

**Issue by FrancescoPerrone** [FrancescoPerrone/melt_maps#4]
@joshjshea has auth problem when pushing changes/branches and the like @FrancescoPerrone needs to check that!

**Comment by OlivineOverlord** [comment]
using GitHub desktop to circumvent issues with the terminal log in

**Comment by FrancescoPerrone** [comment]
> @joshjshea has auth problem when pushing changes/branches and the like @FrancescoPerrone needs to check that!

I’ve just resolve a similar issue I had. You need to check you are using ssh to log in and not https. 

I’ll talk you through the process of needed.
